#! /usr/bin/python2
'''
Python script to parse JSON makefiles.

@author: Sam Agnew
'''
import sys
import json
import subprocess
import os
import functions
import JSONMaker
import MakeFileConverter

if not functions.isFileInDir('JSONMakefile'):
    with functions.openIgnoreCase('Makefile') as mf:
        #I will allow the user to know that I am creating a makefile for them if they do not already have one
        print "Creating JSONMakefile"
        MakeFileConverter.convert(mf)

try:
    with functions.openIgnoreCase('JSONMakefile') as f:
        makeFile = json.load(f)
except IOError:
    print >> sys.stderr, "Error! No Makefile or JSONMakefile in this directory!"
    sys.exit()
except ValueError, e:
    print >> sys.stderr, "Error! Invalid JSON: " + str(e)
    sys.exit()

builder = JSONMaker.JSONMaker(makeFile)

try:
    if len(sys.argv) == 2:
        builder.build(sys.argv[1])
    elif len(sys.argv) == 1:
        builder.build('all')
    else:
        print >> sys.stderr,  "Usage: JSONMake [target]"
        sys.exit(1)
except subprocess.CalledProcessError as e:
    print >> sys.stderr, e.output
    sys.exit()
except KeyError as e:
    #Printing out a message was dealt with already
    sys.exit()

print "Build successful!"
